apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-rc
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
            # ports:
            #   - containerPort: <Port>
