---
# handlers file for deploy_nginx_web

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Restart and enable nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
