apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
# spec:
#   type: NodePort
#   selector:
#     app: my-nginx
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30010

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myappbackend
# spec:
#   type: ClusterIP
#   selector:
#     app: my-nginx
#   ports:
#   - port: 80
#     targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        env: dev
    spec:
      containers:
      - name: my-nginx
        image: nginx
