apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    name: two-containers
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
      - containerPort: 80
  - name: ubuntu
    image: ubuntu
    volumeMounts:
      - name: shared-data
        mountPath: /pod-data
    command: ["bin/bash"]
    args: ["-c","while true; do echo Hello from ubuntu container date: $(date)> /pod-data/index.html; sleep 1; done"]
  volumes:
    - name: shared-data
      emptyDir: {}