apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  ttlSecondsAfterFinished: 30
  # parallelism: 2
  # completions: 3
  # activeDeadlineSeconds: 25
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: hello
        image: perl:5.34
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"] 
      restartPolicy: Never
