apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  labels:
    name: k8s-service
    env: dev
spec:
  type: NodePort
  selector:
    app: http-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
