apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-k8s2-deployment
  template:
    metadata:
      labels:
        app: kgb2
    spec:
      containers:
      - name: kgb2-app
        image: nginx
        ports:
        - containerPort: 80
