apiVersion: v1
kind: Service
metadata:
  name: my-single-pod2-service
  labels:
    env   : prod
    owner : spirt
spec:
  type: LoadBalancer
  selector:
    app: kgb2
  ports:
  - name      : app2-listener
    protocol  : TCP
    port      : 80
    targetPort: 80
