apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    env: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        env: dev
    spec:
      containers:
      - name: my-nginx
        image: nginx
 
        # resources:
        #   limits:
        #     memory: "128M
        #     i"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
