apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app: my-k8s-app
    env: prod
    owner: spirt
spec:
  replicas: 3
  selector:
    matchLabels:
      project: devops
  template:
    metadata:
      labels:
        project: devops
    spec:
      containers:
        - name: devops-app
          image: ingeb0rga/myk8sapp
          ports:
            - containerPort: 80

