# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-web-deployment-autoscaling
#   labels:
#     app: my-k8s-app
#     env: prod
#     owner: spirt
# spec:
#   selector:
#     matchLabels:
#       project: gcp
#   template:
#     metadata:
#       labels:
#         project: gcp
#     spec:
#       containers:
#         - name: devops-app2
#           image: ingeb0rga/myk8sapp
#           ports:
#             - containerPort: 80

# ---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

