apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
    app: main
    tier: frontend
    owner: spirt
spec:
  containers:
    - name: container-apache
      image: nginx
      ports:
        - containerPort: 80

    # - name: container-tomcat
    #   image: tomcat
    #   ports:
    #     - containerPort: 8080