apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-k8s1-deployment
  template:
    metadata:
      labels:
        app: kgb1
    spec:
      containers:
      - name: kgb1-app
        image: httpd
        ports:
        - containerPort: 80
