---
- name: Install JAVA and Jenkins
  hosts: all
  become: true

  tasks:

    - name: Debian
      block:

        - name: Install JAVA
          apt:
            update_cache: true
            name:
              - openjdk-11-jre
              - openjdk-11-jdk
            state: present
          
        - name: Prepare Jenkins install
          shell: |
            curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
            echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

        - name: Install Jenkins
          apt:
            update_cache: true
            name: jenkins
            state: present
          ignore_errors: yes

        - name: Start and enable Jenkins
          service:
            name: jenkins
            state: restarted
            enabled: yes            
              
      when: ansible_os_family == "Debian"