---
- name: Error handling
  hosts: localhost
  connection: local

  tasks:

  - name: task1
    shell: echo "Hello World!"
    register: result
    failed_when: "'World' in result.stdout"

  - name: task2
    debug:
      var: result

  - name: task3
    shell: echo "Hi Azure!"
