apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-k8s-deployment
  template:
    metadata:
      labels:
        app: kgb
    spec:
      containers:
      - name: kgb-app
        image: ingeb0rga/myk8sapp
        ports:
        - containerPort: 80
